# Generated by Django 5.1.3 on 2024-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('staff', 'Staff'), ('sys_admin', 'System Administrator'), ('engineer', 'Engineer'), ('manager', 'Manager')], max_length=100, unique=True)),
            ],
        ),
    ]
