# Generated by Django 5.1.4 on 2025-01-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scan_date', models.DateTimeField()),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('informational_risk_count', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('report', models.JSONField()),
            ],
        ),
    ]
