# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scan.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nscan.proto\x12\x04scan\"\x1a\n\x0bScanRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\".\n\x0cScanResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t2?\n\x0bScanService\x12\x30\n\x07ScanUrl\x12\x11.scan.ScanRequest\x1a\x12.scan.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANREQUEST']._serialized_start=20
  _globals['_SCANREQUEST']._serialized_end=46
  _globals['_SCANRESPONSE']._serialized_start=48
  _globals['_SCANRESPONSE']._serialized_end=94
  _globals['_SCANSERVICE']._serialized_start=96
  _globals['_SCANSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
