# Generated by Django 5.1.3 on 2024-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bankaccounts',
            new_name='Bankaccount',
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
