# Generated by Django 5.1.3 on 2024-12-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0002_rename_bankaccounts_bankaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sendig_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='RBAC.client'),
        ),
    ]
