# Generated by Django 5.1.3 on 2024-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0003_remove_transaction_sendig_account_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('retrieve', 'Retrieve')], default='deposit', max_length=10),
        ),
    ]
