# Generated by Django 5.1.3 on 2025-01-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('report', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('param', models.CharField(max_length=255)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('cwe_id', models.CharField(blank=True, max_length=20, null=True)),
                ('wasc_id', models.CharField(blank=True, max_length=20, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanner.scan')),
            ],
        ),
    ]
