# Generated by Django 5.1.3 on 2025-01-02 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scan_date',
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='confidence',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='cwe_id',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(default='Unnamed Alert', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='param',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], default='Informational', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.URLField(default='http://example.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='wasc_id',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='scan',
            name='report',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='target_url',
            field=models.URLField(max_length=500),
        ),
    ]
