# Generated by Django 5.1.3 on 2025-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_scan_scan_date_alert_created_at_scan_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
