# Generated by Django 5.1.3 on 2024-12-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
